repos:
    -   repo: local
        hooks:
            -   id: autoflake
                name: autoflake
                entry: poetry run autoflake
                language: system
                types: [python]
                args: ["--in-place", "--recursive", "."]
                verbose: true
                require_serial: True
            -   id: isort
                name: isort
                entry: poetry run isort .
                language: system
                types: [python]
                verbose: true
            -   id: black
                name: black
                entry: poetry run black .
                language: system
                types: [python]
                verbose: true
