FROM python:3.8-buster

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ffmpeg \
        libffi-dev \
        python-dev && \
    rm -rf /var/lib/apt/lists* && \
    apt-get -y autoremove && \
    apt-get -y autoclean